/*
 * Author       : OBKoro1
 * Date         : 2022-01-12 14:16:59
 * LastEditors  : OBKoro1
 * LastEditTime : 2022-10-12 23:23:28
 * FilePath     : /src/utils/default-setting/tip-arr.js
 * description  : 默认内容随机提示数组
 * koroFileheader VSCode插件
 * Copyright (c) 2022 by OBKoro1, All Rights Reserved.
 */

export const tipArr = [
  // 方法论
  '刻意练习的四要素，定义明确的目标，极度的专注，有效的反馈，在拉伸区练习。',
  '最好是形成一个知识体系，需要自己沉淀出思维框架，可以逐步提高快速的学习与解决问题的能力',
  '识别高收益，长半衰期的知识。不断加深自己的核心竞争力和不可替代性。',
  '专注的力量非常重要, 选择合适的目标，有所为，有所不为.\n巴菲特的双目标清单: \n巴菲特让朋友圈出职业生涯最重要的20个目标，然后又让他圈出最重要的五个目标。然后告诉他要全力去做五个目标，像躲避瘟疫一样去躲避另外的十五个目标。',
  '有时候你需要适当休息, 试试番茄工作法，太过用力容易导致自我损伤，如果你太过强迫自己去做某件事，就会不断内耗很难长久的坚持下去。',
  '如果想要在某个领域做的出色，就必须对它有强烈的兴趣',
  '模仿最优秀人的人生哲学，你也会更容易接近成功',
  '不要让闲扯淡的人，打扰到做正事的人。',
  '多做重要而不紧急的事情, 合理规划时间成为一个从容的人。',
  '一个人时间用在哪儿，成就就在哪儿。',
  '用进废退: 只有练习才能精进，对于技能树的点击要有所取舍',

  // 思维
  '目标要定在月亮之上，\n即使失败，\n也可以落在众星之间。',
  '目标感非常重要，理清你做事情的方法和路径，为了什么东西去努力。',
  '人们总会高估自己短期的能力，而低估自己长期的能力。',
  '或许每个优秀的人，都有一段沉默的时光。\n在这段时光里付出了很多努力，却得不到想要的结果。\n我们把它叫做扎根。',
  '自古以来学有建树的人，都离不开一个“苦”字。',
  '我从来不认为半小时是微不足道的一段时间 - 达尔文',
  '留下来的经典书籍都是最优秀的人的智慧结晶，想想自己何德何能能与世界最聪明最优秀的人聊天学习，读书就是让你可以轻易的与他们聊天学习，这就是所谓的站在巨人的肩膀上.',
  '读书能让人以最低的成本，去培养眼界和格局。',
  '习惯的力量，好的习惯事半功倍，坏的习惯纠正起来非常难',
  '一身行囊离开的时候，除了一些积蓄，\n就是你的经历，你的态度，你的身体，还有，你的技术。',
  '人在生活中可能会遭到沉重的打击，每一次不幸都是吸取教训的良机。',

  // 哲学
  '真正的成功只有一种，那就是按照自己的方式度过一生',
  '人生是一场马拉松, 一个人一辈子，只要做好一件事就可以了',
  '每天都做那件有意义的事，做的天数多了，人生就有意义了。',

  // 励志语录
  '不怕苦，苦半辈子；\n怕苦，苦一辈子。',
  '失败只有一种，那就是放弃努力, 半途而废。',
  '种一棵树最好的时间是在十年前, \n其次就是现在了。',
  '能不能实现目标，取决于你有多想实现它',
  '心流状态：\n心流是一种将大脑毫不费力的集中起来的状态，这种状态下可以使人忘却时间的概念, 这是一种极度专注的状态。',
  '不吃读书的苦，你就要吃生活的苦，读书是为了让你少吃苦。',
  '你总觉得还有时间，这就是问题所在。',
  '各行各业最优秀的人才每一个都拥有持续阅读，持续学习的习惯，这才是成功的秘诀。',
  '获得某件你想要的东西，最可靠的方法是让自己配得上他。',
  '生活由许许多多小的选择组成，\n每个选择都倾向于舒服的，\n最终将一事无成。',
  '25~35岁，是每个人最宝贵的时光，应该用在刀刃上。',
  '坚持做自己懒得做但正确的事情，\n就能得到别人想得到却得不到的东西。',
  '要想翻过一堵墙，最好的办法是先把帽子扔过去。',
  '学历代表过去、能力代表现在、学习力代表未来。',
  '三延四拖，你就是时间的小偷。',
  '胜利者往往是以坚持最后五分钟的时间中得来成功 - 牛顿',
  '明日复明日，明日何其多。\n日日传明日，万事成蹉跎。\n世人皆被明日累，明日无穷老将至。\n晨昏滚滚水东流，今古悠悠日西坠。\n百年明日能几何，请君听我明日歌。',
  '百金买骏马，\n千金买美人，\n万金买高爵，\n何处买青春？\n',
  '花有重开日，人无再少年。',
  '泰山不让土壤，故能成其大；\n江海不择细流，故能就其深。',
  '九层之台，起于累土。',
  '不问收获，但问耕耘，天道酬勤！',
  '忙于采集的蜜蜂，无暇在人前高谈阔论。',
  '一寸光阴一寸金，寸金难买寸光阴。',
  '勤奋的人是时间的主人，懒惰的人是时间的奴隶。',
  '黑发不知勤学早，白首方悔读书迟。',
  '形成天才的决定因素应该是勤奋。',
  '少壮不努力，老大徒伤悲。',
  '勤奋和智慧是双胞胎，懒惰和愚蠢是亲兄弟。',
  '天行健，君子以自强不息。',
  '玉不琢，不成器；\n木不雕，不成材；\n人不学，不知理。',
  '不经一番寒彻骨，怎得梅花扑鼻香？',
  '笨鸟先飞的觉悟, 愚公移山的坚持。',
  '不积跬步，无以至千里；不积小流，无以成江海。',
  '合抱之木，生于毫末；\n百丈之台，起于累土；\n千里之行，始于足下。',
  '再长的路，一步步也能走完。\n再短的路，不迈开双脚也无法到达。',
  '宝剑锋从磨砺出   梅花香自苦寒来',
  '日日行，不怕千万里；常常做，不怕千万事。',
  '路漫漫其修道远，吾将上下而求索。',
  '质变都来自于量变的积累',
  '书山有路勤为径，学海无涯苦作舟。',
  '世上无难事，只要肯登攀。',
  '勤能补拙是良训，一分耕耘一分才。',
  '不经历风雨，怎能见彩虹？',
  '业精于勤而荒于嬉，行成于思而毁于随。',

  // TODO: 激烈
  // '废物',
  // '垃圾',
  // '没用的东西',
]

// TODO:收集国外的名言
export const tipArrEn = [
  'The four elements of deliberate practice, clearly defined goals, extreme focus, effective feedback, and practice in the stretch zone',
  'It is better to form a knowledge system, which requires you to precipitate your own thinking framework, so that you can gradually improve the ability to quickly learn and solve problems',
  'Identify high-yield, long-half-life knowledge.  Continuously deepen their core competitiveness and irreplaceability',
  '\n Buffett is Double Goal List \n Buffett asked a friend to circle the top 20 goals in his career, and then asked him to circle the top five. Then tell him to focus on the five goals and avoid the other fifteen goals like the plague',
  'Sometimes you need a break. Try the Pomodoro technique. If you push yourself too hard, it can lead to self-injury',
  'If you want to do well in a field, you must have a strong interest in it',
  'Imitate the philosophy of the best and you will come closer to success',
  'Do not let the chatter disturb the man who is doing his work',
  'Do more important but not urgent things, reasonable time management become a leisurely person',
  "Where one spends one's time, one's achievements are there",
  'Use it or lose it: Practice is the only way to get better, be selective about what you click on the skill tree',
  'Aim above the moon, \n can fall among the stars even if it fails',
  "It's important to have a sense of purpose, to figure out how you're going to do things and what you're going to work towards",
  'People tend to overestimate their abilities in the short term and underestimate their abilities in the long term',
  'Perhaps every good person has a period of silence.  \n Put in a lot of effort during this time, but did not get the desired result.  \n We call it rooted',
  "Since ancient times, people have made great achievements, can not be separated from a 'bitter' word",
  'I have never thought half an hour an insignificant amount of time - Darwin',
  'The classic books left behind are the crystallization of the wisdom of the best people. Think about how you can chat and learn with the smartest and best people in the world. Reading is to make you can chat and learn with them easily, which is the so-called standing on the shoulders of giants',
  'Reading allows one to develop vision and structure at the lowest cost',
  'The power of habit, good habits get twice the result with half the effort, bad habits are very difficult to correct',
  'When you leave, in addition to some savings, \n is your experience, your attitude, your body, and your skills',
  'Life can be hard hit, and every misfortune is an opportunity to learn from it',
  'There is only one true success, and that is to spend your life in your own way',
  'Life is a marathon, a person for a lifetime, as long as you do one thing',
  'Do that meaningful thing every day. The more days you do, the more life will be meaningful',
  'Not afraid of bitter, bitter half a lifetime; \n Fear of bitter, bitter life',
  'There is only one kind of failure, that is to give up trying, give up halfway',
  'The best time to plant a tree was ten years ago. The second best time is now',
  'It depends on how much you want it ',
  'Flow: Flow is a state of effortless concentration of the mind that makes one lose track of time. It is a state of intense concentration',
  "Don't eat the pain of reading, you will eat the pain of life, reading is to let you suffer less",
  "You always think there's time, that's the problem",
  'The secret of success is that the best minds in all walks of life keep reading and learning',
  'The surest way to get something you want is to be worthy of it',
  'Life is made up of a lot of small choices, \n each of which tends to be comfortable, \n ultimately leads nowhere',
  "25~35 years old, is everyone's most precious time, should be used in the best",
  "Keep doing the right thing that you are too lazy to do, and you will get what others want but can't get",
  'The best way to get over a wall is to throw your hat over it. ',
  'Education represents the past, ability represents the present, learning ability represents the future',
  'You are the thief of time',
  'Winners often succeed by hanging on for the last five minutes - Newton',
  'Tomorrow and tomorrow, and so many tomorrow. n day by day tomorrow, everything into waste. The world is tired of tomorrow, tomorrow is old. n rolling water flow in the east, today ancient leisurely day west fall. n hundred years tomorrow can geometry, please listen to my song tomorrow',
  'Hundred gold to buy a horse, n gold to buy beauty, n million gold to buy high jue, n where to buy youth? \n, A flower may bloom again, but a man shall never be young again',
  'Mount Tai does not let the soil, so it can become its big; n The river does not choose a small stream, so it can be deep',
  'A platform of nine layers rises from soil',
  "Don't ask the harvest, but ask the ploughing, God rewards the diligent!",
  'Busy gathering bees, no time to talk in front of people',
  "An inch of time is an inch of gold, and an inch of gold can't buy an inch of time",
  'The diligent man is the master of time, and the lazy man is the slave of time',
  'Black hair do not know study early, whitehead party regret reading late',
  'The determinant of genius should be diligence',
  'A young idler, an old beggar',
  'Diligence and wisdom are twins; idleness and folly are brothers',
  'Heaven moves vigorously, a gentleman to self-improvement',
  'The best cut is the best cut; \n No wood carved, no wood; \n people who do not learn know nothing',
  'Without a cold to the bone, how to get the plum smell fragrant?',
  'The consciousness of the foolish bird flies first, the persistence of the foolish man',
  'Short step, no miles; Do not accumulate small flow, beyond into Jianghai',
  'The folded wood was born at the end of a millimetre; n hundred feet of the Taiwan, from the tired soil; \n A journey of a thousand miles begins with a single step',
  'A long road can be completed step by step. n Again short road, do not stride feet can not reach',
  'Bao Jianfeng honed plum blossom fragrance from the bitter cold',
  'Day, not afraid of thousands of miles; Often do, not afraid of everything',
  'There is a long way to go, and I will seek it up and down.',
  'Qualitative change comes from the accumulation of quantitative change',
  'Books have a path, learning is long and hard',
  'Nothing is difficult to the man who will try',
  'Diligent can make up stupid is good training, no pains no ability ',
  'How can we see the rainbow without the storm? ',
  'Practice is excellent in diligence and scarcity in one, success in thought and destruction in follow',
]
